meta_data:
  script_path: run_scripts/ppo_exp_script.py
  exp_name: test_ppo_pendulum
  description: Train an agent using Proximal Policy Optimization
  num_workers: 1
  using_gpus: true
# -----------------------------------------------------------------------------
variables:
  seed: [7294]

# -----------------------------------------------------------------------------
constants:
  net_size: 256
  num_hidden_layers: 2

  rl_alg_params:
    num_epochs: 300
    num_steps_per_epoch: 10000
    num_steps_between_train_calls: 2048
    num_train_steps_per_train_call: 1
    num_steps_per_eval: 10000
    max_path_length: 200
    min_steps_before_training: 2048

    eval_deterministic: true

    # Not used, since PPO use all on-policy data for training
    batch_size: 256
    replay_buffer_size: 1000000
    no_terminal: false
    wrap_absorbing: false

    save_best: false
    freq_saving: 10
    save_replay_buffer: false
    save_environment: false
    save_algorithm: false

  ppo_params:
    clip_eps: 0.2
    reward_scale: 1.0
    discount: 0.99
    policy_lr: 0.0003
    value_lr: 0.0003
    lambda_entropy_policy: 0.0
    gae_tau: 0.95
    value_l2_reg: 0.001
    mini_batch_size: 128
    update_epoch: 10

  env_specs:
    env_creator: "gym"
    env_name: "Pendulum-v0"
    env_kwargs: {}
    env_num: 1
    eval_env_seed: 78236
    training_env_seed: 24495
