meta_data:
  script_path: run_scripts/dagger_exp_script.py
  exp_name: dagger_hopper
  description: Train a DAgger model
  num_workers: 3
  using_gpus: true
# -----------------------------------------------------------------------------
variables:
  seed: [723894, 23789, 440096]

# -----------------------------------------------------------------------------
constants:
  expert_name: 'norm_hopper_32_demos_sub_20'
  expert_idx: 0
  traj_num: 4
  scale_env_with_demo_stats: true

  expert_policy_path: '../hopper_expert.pkl'
  use_deterministic_expert: true
  unscale_for_expert: true

  policy_net_size: 256
  policy_num_hidden_layers: 2

  dagger_params:
    mode: 'MLE'

    num_epochs: 201
    num_steps_per_epoch: 8000
    num_steps_between_train_calls: 8000
    max_path_length: 1000
    min_steps_before_training: 0

    eval_deterministic: true
    num_steps_per_eval: 10000
    
    replay_buffer_size: 2000000
    no_terminal: false
    wrap_absorbing: false

    num_initial_train_steps: 1000
    num_updates_per_train_call: 1000
    lr: 0.0003
    momentum: 0.9
    batch_size: 256

    save_best: true
    save_best_starting_from_epoch: 0

    freq_saving: 20
    save_replay_buffer: false
    save_environment: false
    save_algorithm: false

  env_specs:
    env_name: 'hopper'
    env_kwargs: {}
    eval_env_seed: 78236
    training_env_seed: 24495
