meta_data:
  script_path: run_scripts/her_td3_exp_script.py
  exp_name: her_fetch_reach
  description: Train an her agent using TD3
  num_workers: 2
  using_gpus: true
# -----------------------------------------------------------------------------
variables:
  seed: [723894]

# -----------------------------------------------------------------------------
constants:
  net_size: 256
  num_hidden_layers: 3
  policy_noise: 0.1
  policy_noise_clip: 0.5
  
  # method of goal generation
  # goal_gen: 'interval' # ['vanilla', 'fixobj', 'interval', 'reach']

  rl_alg_params:
    num_epochs: 282
    num_steps_per_epoch: 2500
    num_steps_between_train_calls: 50
    num_train_steps_per_train_call: 20
    num_steps_per_eval: 5000
    max_path_length: 50
    min_steps_before_training: 10000

    eval_deterministic: true

    batch_size: 256
    replay_buffer_size: 10000
    no_terminal: false
    wrap_absorbing: false

    save_best: false
    freq_saving: 10
    save_replay_buffer: false
    save_environment: false
    save_algorithm: false

  td3_params:
    policy_and_target_update_period: 20
    reward_scale: 1.0
    discount: 0.98
    soft_target_tau: 0.005
    policy_lr: 0.001
    qf_lr: 0.001
    clip_return: true

  env_specs:
    env_name: 'fetch-reach'
    env_kwargs: {}
