meta_data:
  script_path: run_scripts/td3_exp_script.py
  exp_name: td3_hopper
  description: Train an agent using TD3
  num_workers: 2
  using_gpus: true
# -----------------------------------------------------------------------------
variables:
  seed: [723894]

# -----------------------------------------------------------------------------
constants:
  net_size: 256
  num_hidden_layers: 2
  policy_noise: 0.1
  policy_noise_clip: 0.5

  rl_alg_params:
    num_epochs: 282
    num_steps_per_epoch: 10000
    num_steps_between_train_calls: 1
    num_train_steps_per_train_call: 1
    num_steps_per_eval: 10000
    max_path_length: 1000
    min_steps_before_training: 2500

    eval_deterministic: true

    batch_size: 256
    replay_buffer_size: 1000000
    no_terminal: false
    wrap_absorbing: false

    save_best: false
    freq_saving: 10
    save_replay_buffer: false
    save_environment: false
    save_algorithm: false

  td3_params:
    policy_and_target_update_period: 2
    reward_scale: 1.0
    discount: 0.99
    soft_target_tau: 0.005
    policy_lr: 0.0003
    qf_lr: 0.0003

  env_specs:
    env_name: 'hopper'
    env_kwargs: {}
    eval_env_seed: 78236
    training_env_seed: 24495
